import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'app/app.dart';
import 'firebase_options.dart';

// NOTE: `firebase_options.dart` does not exist yet — it is generated by the
// FlutterFire CLI (`flutterfire configure`), which needs to run once against
// your own Firebase project. See the setup steps for this project. Until
// that file exists, this app will fail to build.

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  runApp(const ChurchMateApp());
}
